export const ROOT_ACTION_TYPES = {
  ROOT_CHANGED: 'ROOT_CHANGED',
};

/* export const USER_ACTION_TYPES = {
  FETCH_USER_PROFILE: 'FETCH_USER_PROFILE',
  FETCH_USER_PROFILE_PENDING: 'FETCH_USER_PROFILE_PENDING',
  FETCH_USER_PROFILE_FULFILLED: 'FETCH_USER_PROFILE_FULFILLED',
  FETCH_USER_PROFILE_REJECTED: 'FETCH_USER_PROFILE_REJECTED',
}; */
