export const ROOT_ACTION_TYPES = {
  ROOT_CHANGED: 'ROOT_CHANGED',
};

export const AUTH_ACTION_TYPES = {
  LOGIN_USER: 'LOGIN_USER',
  SIGNOUT_USER: 'SIGNOUT_USER',
  LOGIN_USER_PENDING: 'LOGIN_USER_PENDING',
  LOGIN_USER_FULFILLED: 'LOGIN_USER_FULFILLED',
  LOGIN_USER_REJECTED: 'LOGIN_USER_REJECTED',

  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_PENDING: 'REGISTER_USER_PENDING',
  REGISTER_USER_FULFILLED: 'REGISTER_USER_FULFILLED',
  REGISTER_USER_REJECTED: 'REGISTER_USER_REJECTED',

  LOGIN_PROVIDER: 'LOGIN_PROVIDER',
  LOGIN_PROVIDER_PENDING: 'LOGIN_PROVIDER_PENDING',
  LOGIN_PROVIDER_FULFILLED: 'LOGIN_PROVIDER_FULFILLED',
  LOGIN_PROVIDER_REJECTED: 'LOGIN_PROVIDER_REJECTED',

  REGISTER_PROVIDER: 'REGISTER_PROVIDER',
  REGISTER_PROVIDER_PENDING: 'REGISTER_PROVIDER_PENDING',
  REGISTER_PROVIDER_FULFILLED: 'REGISTER_PROVIDER_FULFILLED',
  REGISTER_PROVIDER_REJECTED: 'REGISTER_PROVIDER_REJECTED',
};

/* export const USER_ACTION_TYPES = {
  FETCH_USER_PROFILE: 'FETCH_USER_PROFILE',
  FETCH_USER_PROFILE_PENDING: 'FETCH_USER_PROFILE_PENDING',
  FETCH_USER_PROFILE_FULFILLED: 'FETCH_USER_PROFILE_FULFILLED',
  FETCH_USER_PROFILE_REJECTED: 'FETCH_USER_PROFILE_REJECTED',
}; */
