# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'wevedo_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wevedo_app
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  platform :ios, '9.0'  
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  target 'wevedo_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'wevedo_app-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wevedo_app-tvOS

  target 'wevedo_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
