# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'wevedo_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wevedo_app
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  platform :ios, '9.0'  
  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  target 'wevedo_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'wevedo_app-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wevedo_app-tvOS

  target 'wevedo_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
